=== elangovanrxw/RwxTraining/XSDforXMLexercise/src/main/resources/featureMetaInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"  
		elementFormDefault="qualified">
		
<import namespace="http://attunedlabs.com/internal/FeatureMetaInfoSupporting" schemaLocation="FeatureMetaInfoSupporting.xsd" />
		
<element name="Feature-Metainfo">
	<complexType>
		<sequence>
			<element name="FeatureGroup">
				<complexType>
					<sequence>
						<element name="Name" type="string" />
						<element name="Features">
							<complexType>
								<sequence>
									<element name="Feature" minOccurs="1" maxOccurs="unbounded">
										<complexType>
											<sequence>
												<element name="Name" type="string" />
												<element name="FeatureImplementations">
													<complexType>
														<sequence>
															<element name="FeatureImplementation" minOccurs="1" maxOccurs="unbounded">
																<complexType>
																	<attribute name="resourceName" type="string" use="required" />
																</complexType>
															</element>
														</sequence>
													</complexType>
												</element>
												<element name="StaticFileConfiguration">
													<complexType>
														<sequence>
															<element name="ConfigFile" minOccurs="1" maxOccurs="1">
																<complexType>
																	<attribute name="filePath" type="string" use="required" />
																	<attribute name="fileName" type="string" use="required" />
																</complexType>
															</element>
														</sequence>
													</complexType>
												</element>
												
												<element name="DBConfiguration">
													<complexType>
														<sequence>
															<element name="database">
																<complexType>
																	<sequence>
																		<element name="table" minOccurs="1" maxOccurs="unbounded">
																			<complexType>
																				<sequence>
																					<element name="column" minOccurs="1" maxOccurs="unbounded">
																						<complexType>
																							<attribute name="name" type="string" use="required" />
																							<attribute name="type" type="string" use="required" />
																							<attribute name="primaryKey" type="boolean" use="optional" />
																							<attribute name="required" type="boolean" use="optional" />
																							<attribute name="autoIncrement" type="boolean" use="optional" />
																							<attribute name="size" type="int" use="optional" />
																						</complexType>
																					</element>
																				</sequence>
																				<attribute name="name" type="string" use="required"></attribute>
																			</complexType>
																		</element>
																	</sequence>
																	<attribute name="name" type="string" use="required"/>
																</complexType>
															</element>
														</sequence>
													</complexType>
												</element>
											</sequence>
											<attribute name="vendorName" type="string" use="required"/>
											<attribute name="vendorVersion" type="float" use="required"/>
											<attribute name="implementationName" type="string" use="required"/>
										</complexType>
									</element>
								</sequence>
							</complexType>
						
						</element>
					</sequence>
				</complexType>
			</element>
		</sequence>
		<attribute name="productVersion" type="string" use="required" />
	</complexType>

</element>
</schema>

=== elangovanrxw/RwxTraining/jaxbexercise2/featureMetaInfo_new.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Feature-Metainfo xmlns:fms="http://attunedlabs.com/internal/FeatureMetaInfoSupporting" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" productVersion="WMS2.0" xsi:noNamespaceSchemaLocation="featureMetaInfo.xsd">
    <FeatureGroup>
        <Name>ddlUtilGroup</Name>
        <Features>
            <Feature vendorName="attunedlabs" vendorVersion="1.0" implementationName="attunedlabs">
                <Name>ddl</Name>
                <FeatureImplementations>
                    <FeatureImplementation resourceName="sac-key2act-globalFeatureservice.xml"/>
                </FeatureImplementations>
                <StaticFileConfiguration>
                    <ConfigFile filePath="/home/paul/XSLTFiles/" fileName="ftlSubjectTemplate.ftl"/>
                </StaticFileConfiguration>
                <DBConfiguration>
                    <database name="leap_new">
                        <table name="author">
                            <column name="author_id" type="INTEGER" primaryKey="true" required="true" autoIncrement="false"/>
                            <column name="name" type="VARCHAR" required="true" size="50"/>
                            <column name="surName" type="VARCHAR" required="false" size="50"/>
                            <column name="organization" type="VARCHAR" required="false" size="50"/>
                        </table>
                        <table name="book">
                            <column name="book_id" type="INTEGER" primaryKey="true" required="true" autoIncrement="true"/>
                            <column name="author_id" type="INTEGER" required="true"/>
                            <column name="title" type="VARCHAR" required="true" size="255"/>
                        </table>
                    </database>
                </DBConfiguration>
            </Feature>
            <Feature vendorName="attunedlabs" vendorVersion="1.0" implementationName="attunedlabs">
                <Name>ddl</Name>
                <FeatureImplementations>
                    <FeatureImplementation resourceName="sac-key2act-globalFeatureservice.xml"/>
                </FeatureImplementations>
                <StaticFileConfiguration>
                    <ConfigFile filePath="/home/paul/XSLTFiles/" fileName="ftlSubjectTemplate.ftl"/>
                </StaticFileConfiguration>
                <DBConfiguration>
                    <database name="leap_new">
                        <table name="author">
                            <column name="author_id" type="INTEGER" primaryKey="true" required="true" autoIncrement="false"/>
                            <column name="name" type="VARCHAR" required="true" size="50"/>
                            <column name="surName" type="VARCHAR" required="false" size="50"/>
                            <column name="organization" type="VARCHAR" required="false" size="50"/>
                        </table>
                        <table name="book">
                            <column name="book_id" type="INTEGER" primaryKey="true" required="true" autoIncrement="true"/>
                            <column name="author_id" type="INTEGER" required="true"/>
                            <column name="title" type="VARCHAR" required="true" size="255"/>
                        </table>
                    </database>
                </DBConfiguration>
            </Feature>
        </Features>
    </FeatureGroup>
</Feature-Metainfo>
